Moved hard mode to settings modal
cwackerfuss/react-wordle pull request #146
Opened 2022-02-10 15:12 UTC by TheKnowles

Removed unclear toggable hardmode icons. Moved hard mode setting to a settings modal popup. This setup closely aligns with the source material.

Fixes https://github.com/cwackerfuss/react-wordle/issues/37

2022-02-10 17:23 UTC, gheja commented
I really like this as this opens up the possibility to add more settings without cluttering the main screen.

2022-02-10 20:06 UTC, TheKnowles commented
@diondiondion great catch! I didn't try phone mode on the browser before submitting. I've added a minimum gap to the dialog.

+1 for moving dark mote into settings as well, I'll wait for consensus before making that change.

2022-02-11 15:34 UTC, cwackerfuss requested changes
thanks @TheKnowles ! 

Couple minor tweaks:
- Let's abstract the toggle into a separate component
- Can you add cursor-pointer to the toggle

2022-02-11 15:37 UTC, cwackerfuss commented
We just got a fancy new animation from @abrarhayat for darkmode/lightmode, but I think if we do decide to move dark mode to the settings modal, it should just be a toggle like hardmode, to be consistent (sorry @abrarhayat). I vote yes to moving it as well.

2022-02-11 15:55 UTC, TheKnowles commented
@cwackerfuss we now have a reusable component for future toggleable settings. I've moved dark mode into settings.

2022-02-11 16:01 UTC, cwackerfuss commented
Yes please!

2022-02-11 16:38 UTC, TheKnowles commented
@cwackerfuss all done! Let me know if I missed anything.

2022-02-11 21:48 UTC, cwackerfuss approved these changes

2022-02-11 21:51 UTC, merged

2022-02-13 12:04 UTC, igitur commented
@TheKnowles This PR should've included instructions for translation in `README.md` similar to the instructions for other dialogs.

2022-02-24 23:10 UTC, muhelen commented
Hi, diid anyone know how to  add description class on this settings? Same like the original? 
<img width="526" alt="Screenshot 2022-02-25 at முற்பகல் 7 08 37" src="https://user-images.githubusercontent.com/5513469/155622890-dc1a2db7-d713-45ea-8335-f95fd62a0c95.png">