Added setting modal descriptions
cwackerfuss/react-wordle pull request #274
Opened 2022-02-25 15:07 UTC by TheKnowles

SettingsToggle can now take optional descriptions. Added hard mode description.

2022-02-25 19:00 UTC, abrarhayat requested changes

2022-02-25 19:21 UTC, TheKnowles commented
@abrarhayat thanks for the review!

Added high contrast mode description and some vertical padding to the description blocks.

2022-02-25 19:29 UTC, abrarhayat approved these changes

2022-02-27 20:01 UTC, cwackerfuss commented
Thanks @TheKnowles you rock. I'm going to approve and merge this and I may just tweak the layout a bit in a followup PR.

2022-02-27 20:01 UTC, cwackerfuss approved these changes

2022-02-27 20:01 UTC, merged