getIndex() + renamed tomorrow to next
cwackerfuss/react-wordle pull request #85
Opened 2022-01-31 22:35 UTC by vvmspace

From https://wordle.uno with ❤️❤️❤️

2022-02-04 15:44 UTC, cwackerfuss requested changes
Looks great, thanks for the thoughtful changes. Just a few comments

2022-02-04 15:44 UTC, cwackerfuss commented on src/App.tsx
> +  const index = getIndex()
`solutionIndex` is already being exported by `./lib/words` so let's just import that and leave `getIndex` unexported for now.

I think the `getWordOfDay` function should be refactored in the near future so we're evaluating the word from React rather than through vanilla JS initialization.

2022-02-04 15:44 UTC, cwackerfuss commented on src/App.tsx
> +        </h1>
Nit: lets remove this from the header, the original game doesn't include the index in the title

2022-02-04 15:44 UTC, cwackerfuss commented on src/components/modals/StatsModal.tsx
> +              date={next}
Nit: while we're changing this, can we be even more expressive and say `nextDayInMs`

2022-02-05 10:06 UTC, vvmspace commented on src/components/modals/StatsModal.tsx
> +              date={next}
I am using 1 hour delay.

2022-02-05 10:09 UTC, vvmspace commented on src/components/modals/StatsModal.tsx
> +              date={next}
May be nextWordInMs?

2022-02-11 19:03 UTC, noemartinez commented on src/lib/words.ts
> +export const START_DATE = '01-01-2022';
I've recently started experimenting with this repo and found that it'd be great to have this constant promoted into ```settings.ts``` and advertised in the README's FAQs as a setting that can be easily adjusted. It might be cool to do that as part of this PR. Thanks for the consideration!

2022-03-02 15:19 UTC, closed without merging

2022-03-02 22:47 UTC, vvmspace commented
Guys, not working on it now. Can someone fix merge conflicts etc?