Adds character animation on completion.
cwackerfuss/react-wordle pull request #97
Opened 2022-02-02 06:06 UTC by wuori

This PR adds a sequence of character reveals similar to the official Wordle app. 

Tested in Chrome 97.0.4692.71 (Mac OSX) and iOS Safari (latest).

Note: I don't work in React much so there may be a better way to hook this in, but the supplied version works fine and even reapplies the animations on page reload.

See GIF for example:  https://imgur.com/dagVbNh

Thank you for sharing this project!

![image](https://imgur.com/dagVbNh)

2022-02-04 15:50 UTC, cwackerfuss requested changes
Looks good, few comments

2022-02-04 15:50 UTC, cwackerfuss commented on src/components/grid/CompletedRow.tsx
> +    const cellShowDelay = 400;
Lets speed this up, with the style of animation, it feels painfully slow. Maybe 100 or 150 ms instead?

2022-02-04 15:50 UTC, cwackerfuss commented on src/components/grid/CompletedRow.tsx
> +  });
It seems like this isn't formatted -- can you please run `npm run fix` and commit? Thank you!

2022-02-04 22:48 UTC, diondiondion commented
The approach of adding CSS classes directly to the DOM is very un-react-y and prone to break (React won't know about those classes and discard them on re-renders).

IMO this should be implemented using simple CSS animations with different `animation-delay` timings, not in JS.

2022-02-04 22:53 UTC, cwackerfuss commented
@diondiondion I was moving too quickly through PRs and totally missed this. Great call out. @wuori does @diondiondion's suggestion make sense to you? 

It will be a little tricky with CSS to get this behavior, but if possible that is the preferred approach. Otherwise a clean JS solution that dynamically adds/removes an animation class to the React child elements (not using dom methods) is also fine

2022-02-09 01:50 UTC, wuori commented
@cwackerfuss Yeah @diondiondion is probably right. I'm not a React developer and didn't consider this, was just playing around and thought it would help make the port more like the original. I'll look into it some more and update this PR if/when I find a better solution.

2022-02-09 01:53 UTC, cwackerfuss commented
I think this was actually added in another pr. Thank you for trying -- closing this

2022-02-09 01:54 UTC, closed without merging